apiVersion: apps/v1
kind: Deployment
metadata:
  name: mortgage-modular
  labels:
    app: mortgage-modular
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mortgage-modular
  template:
    metadata:
      labels:
        app: mortgage-modular
    spec:
      containers:
        - name: mortgage-demo-snaphomz
          image: 075502422618.dkr.ecr.us-west-1.amazonaws.com/mortgage-demo-snaphomz:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: mortgage-frontend-env 
