apiVersion: v1
kind: Service
metadata:
  name: mortgage-modular-service
  labels:
    app: mortgage-modular
spec:
  selector:
    app: mortgage-modular
  type: clusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
