apiVersion: v1
kind: Service
metadata:
  name: mortgage-modular-service
  labels:
    app: mortgage-modular
spec:
  selector:
    app: mortgage-modular
  type: NodePort  # This line is required when using nodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 32089  # Must be between 30000–32767
