apiVersion: apps/v1
kind: Deployment
metadata:
  name: communication-service
  labels:
    app: communication-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: communication-service
  template:
    metadata:
      labels:
        app: communication-service
    spec:
      containers:
      - name: agents-service
        image: 075502422618.dkr.ecr.us-west-1.amazonaws.com/demo/communication-service:latest
        ports:
        - containerPort: 4002
        envFrom:
        - secretRef:
            name: comm-env
      imagePullSecrets:
      - name: ecr-secret
