apiVersion: apps/v1
kind: Deployment
metadata:
  name: communication-service
  labels:
    app: communication-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: communication-service
  template:
    metadata:
      labels:
        app: communication-service
    spec:
      containers:
      - name: communication-service
        image: obi77/communication-service:latest
        ports:
        - containerPort: 4002
        env:
        - name: DOTENV_PATH
          value: "/app/.env"
        volumeMounts:
        - name: env-volume
          mountPath: /app/.env
          subPath: .env
      volumes:
      - name: env-volume
        hostPath:
          path: /home/ubuntu/prod/communication/.env
          type: File
