apiVersion: apps/v1
kind: Deployment
metadata:
  name: snaphomz
  labels:
    app: snaphomz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snaphomz
  template:
    metadata:
      labels:
        app: snaphomz
    spec:
      containers:
      - name: snaphomz
        image: obi77/snaphomz:2025.07.22-59
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
