apiVersion: v1
kind: Service
metadata:
  name: snaphomz
spec:
  selector:
    app: snaphomz
  type: LoadBalancer
  ports:
    - port: 8001        # Port exposed on the LoadBalancer
      targetPort: 8001  # Port on your Pod
      nodePort: 32081   # Optional, only used if type: NodePort or LoadBalancer
      protocol: TCP
      name: http    # Name of the port            
