apiVersion: v1
kind: Service
metadata:
  name: snaphomz
spec:
  selector:
    app: snaphomz
  type: NodePort
  ports:
    - port: 8001          # Service port (used inside cluster)
      targetPort: 8001    # Container port inside pod
      nodePort: 30081     # External port (browser will access this)
      protocol: TCP
