apiVersion: v1
kind: Service
metadata:
  name: snaphomz
spec:
  selector:
    app: snaphomz
  type: ClusterIP
  ports:
    - port: 8001        
      targetPort: 8001  # Port on your Pod
      protocol: TCP
               
