apiVersion: v1
kind: Service
metadata:
  name: snaphomz
spec:
  selector:
    app: snaphomz
  type: ClusterIP
  ports:
    - port: 8001          # Service port (used inside cluster)
      targetPort: 8001    # Container port inside pod
      protocol: TCP
