apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 4000
      nodePort: 32084  # 32084 is arbitrary; just needs to be > 30000 and < 32767