apiVersion: v1
kind: Service
metadata:
  name: preapproval-service
spec:
  selector:
    app: preapproval-service
  type: LoadBalancer
  ports:
    - port: 4004
      targetPort: 4004
      nodePort: 32091  