apiVersion: apps/v1
kind: Deployment
metadata:
  name: snaphomz-ai-search
  labels:
    app: snaphomz-ai-search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snaphomz-ai-search
  template:
    metadata:
      labels:
        app: snaphomz-ai-search
    spec:
      containers:
        - name: ai-demo-snaphomz
          image: 075502422618.dkr.ecr.us-west-1.amazonaws.com/ai-demo-snaphomz:latest
          ports:
            - containerPort: 9000
          envFrom:
            - secretRef:
                name: snaphomz-ai-env  # Inject all variables from secret into env
      # Note: volumeMounts & hostPath removed as they are no longer needed
