apiVersion: v1
kind: Service
metadata:
  name: snaphomz-ai-search
spec:
  selector:
    app: snaphomz-ai-search
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 32088  # 32088 is arbitrary; just needs to be > 30000 and < 32767
