apiVersion: v1
kind: Service
metadata:
  name: snaphomz-ai-search
spec:
  selector:
    app: snaphomz-ai-search
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 32088  # Must be in range 30000-32767
