# ===================== Prometheus Service =====================
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - name: http
      protocol: TCP
      port: 9090
      targetPort: 9090
  type: NodePort  # Use ClusterIP in production, NodePort for testing
  nodePort: 32900  # Optional, specify if you want a fixed port for access  
---
# ===================== Grafana Service =====================
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort  # Use LoadBalancer if running on cloud, ClusterIP in production
  nodePort: 32000  # Optional, specify if you want a fixed port for access