apiVersion: apps/v1
kind: Deployment
metadata:
  name: mortgage-service
  labels:
    app: mortgage-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mortgage-service
  template:
    metadata:
      labels:
        app: mortgage-service
    spec:
      containers:
      - name: mortgage-service
        image: 075502422618.dkr.ecr.us-west-1.amazonaws.com/demo/mortgage-service:latest
        ports:
        - containerPort: 4001
        envFrom:
        - secretRef:
            name: mortgage-env
      imagePullSecrets:
      - name: ecr-secret
