apiVersion: apps/v1
kind: Deployment
metadata:
  name: mortgage-service
  labels:
    app: mortgage-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mortgage-service
  template:
    metadata:
      labels:
        app: mortgage-service
    spec:
      containers:
      - name: mortgage-service
        image: obi77/mortgage-service:latest
        ports:
        - containerPort: 4001
        env:
        - name: DOTENV_PATH
          value: "/app/.env"
        volumeMounts:
        - name: env-volume
          mountPath: /app/.env
          subPath: .env
      volumes:
      - name: env-volume
        hostPath:
          path: /home/ubuntu/prod/mortgage/.env
          type: File
