apiVersion: apps/v1
kind: Deployment
metadata:
  name: agents-service
  labels:
    app: agents-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agents-service
  template:
    metadata:
      labels:
        app: agents-service
    spec:
      containers:
        - name: agents-service
          image: obi77/agents-service:latest
          ports:
            - containerPort: 4003
          envFrom:
            - configMapRef:
                name: dotenv-config
          volumeMounts:
            - name: env-volume
              mountPath: /app/.env
              subPath: .env
              readOnly: true
      volumes:
        - name: env-volume
          hostPath:
            path: /home/ec2-user/prod/agents/.env  # Ensure this is the correct path on your EC2 machine
            type: File
