apiVersion: apps/v1
kind: Deployment
metadata:
  name: agents-service
  labels:
    app: agents-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agents-service
  template:
    metadata:
      labels:
        app: agents-service
    spec:
      containers:
      - name: agents-service
        image: 075502422618.dkr.ecr.us-west-1.amazonaws.com/demo/agents-service:latest
        ports:
        - containerPort: 4003
        envFrom:
        - secretRef:
            name: agents-env
      imagePullSecrets:
      - name: ecr-secret
