apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-frontend
  labels:
    app: agent-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-frontend
  template:
    metadata:
      labels:
        app: agent-frontend
    spec:
      containers:
        - name: agent-demo-snaphomz
          image: 075502422618.dkr.ecr.us-west-1.amazonaws.com/agent-demo-snaphomz:latest
          ports:
            - containerPort: 3000
          envfrom:
            - secretref:
                name: agent-frontend-env 
                
