apiVersion: v1
kind: Service
metadata:
  name: agent-frontend
spec:
  selector:
    app: agent-frontend
  type: LoadBalancer
  ports:
    - port: 3000
      protocol: TCP # Ensure this matches the containerPort in deployment yaml
      # The following fields are optional; uncomment if you want to specify them    
      targetPort: 3000
      nodePort: 32082  # 32082 is arbitrary; just needs to be > 30000 and < 32767