apiVersion: v1
kind: Service
metadata:
  name: agent-frontend
  labels:
    app: agent-frontend
spec:
  selector:
    app: agent-frontend
  type: ClusterIP   
  ports:
    - port: 3000           # Exposed port inside cluster
      targetPort: 3000     # Matches the containerPort in deployment
      protocol: TCP
