apiVersion: v1
kind: Service
metadata:
  name: agent-frontend-service
  labels:
    app: agent-frontend
spec:
  type: LoadBalancer
  selector:
    app: agent-frontend
  ports:
    - protocol: TCP
      port: 3000         # Externally exposed port
      targetPort: 3000   # Port your container listens on
  