apiVersion: apps/v1
kind: Deployment
metadata:
  name: snaphomz-waitlist
  labels:
    app: snaphomz-waitlist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snaphomz-waitlist
  template:
    metadata:
      labels:
        app: snaphomz-waitlist
    spec:
      containers:
      - name: snaphomz-waitlist
        image: obi77/snaphomz_waitlist:latest
        ports:
        - containerPort: 8002
        imagePullPolicy: Always