apiVersion: apps/v1
kind: Deployment
metadata:
  name: snaphomz_waitlist
  labels:
    app: snaphomz_waitlist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snaphomz_waitlist
  template:
    metadata:
      labels:
        app: snaphomz_waitlist
    spec:
      containers:
      - name: snaphomz
        image: obi77/snaphomz_waitlist:latest
        ports:
        - containerPort: 8000
