apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: npm-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: npm-pv             # <-- must match PV name
  storageClassName: ""           # <-- disable dynamic provisioning
