apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: npm-data
  namespace: default  # Change this if you're deploying in another namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ""  # Use default StorageClass

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: npm-letsencrypt
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""  # Use default StorageClass
