apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy-manager
spec:
  type: NodePort
  selector:
    app: nginx-proxy-manager
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30095
    - port: 81
      targetPort: 81
      nodePort: 30096
    - port: 443
      targetPort: 443
      nodePort: 30443
