apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy-manager
spec:
  type: NodePort
  selector:
    app: nginx-proxy-manager
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
    - port: 81
      targetPort: 81
      nodePort: 30081
    - port: 443
      targetPort: 443
      nodePort: 30443
