apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy-manager
spec:
  type: NodePort  # or LoadBalancer if using cloud provider
  selector:
    app: nginx-proxy-manager
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30095
    - name: admin
      port: 81
      targetPort: 81
      nodePort: 30091
    - name: https
      port: 443
      targetPort: 443
      nodePort: 30443
