apiVersion: apps/v1
kind: Deployment
metadata:
  name: zip-service
  labels:
    app: zip-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zip-service
  template:
    metadata:
      labels:
        app: zip-service
    spec:
      containers:
      - name: zip-service
        image: obi77/zip-service:latest
        ports:
        - containerPort: 5050
        env:
        - name: DOTENV_PATH
          value: "/app/.env"
        volumeMounts:
        - name: env-volume
          mountPath: /app/.env
          subPath: .env
      volumes:
      - name: env-volume
        secret:
          secretName: zipform-env
