apiVersion: apps/v1
kind: Deployment
metadata:
  name: zip-service
  labels:
    app: zip-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zip-service
  template:
    metadata:
      labels:
        app: zip-service
    spec:
      containers:
      - name: zip-service
        image: 075502422618.dkr.ecr.us-west-1.amazonaws.com/demo/zip-service:latest
        ports:
        - containerPort: 5050
        envFrom:
        - secretRef:
            name: zip-env
      imagePullSecrets:
      - name: ecr-secret
