apiVersion: v1
kind: Service
metadata:
  name: zip-service
spec:
  selector:
    app: zip-service
  type: LoadBalancer
  ports:
    - port: 5050
      targetPort: 5050
      nodePort: 32087  # 32087 is arbitrary; just needs to be > 30000 and < 32767
